kind: pipeline
type: docker
name: 盘古


clone:
  disable: true


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      test:
        enabled: false
      compress:
        enabled: false

  - name: 文档
    image: dronestock/node
    settings:
      folder: doc

  - name: 部署
    image: dronestock/cos
    settings:
      folder: doc/dist
      secret_id:
        from_secret: secret_id_cos
      secret_key:
        from_secret: secret_key_cos
      base_url: https://pangu-1253228583.cos.ap-chengdu.myqcloud.com


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
