kind: secret
name: token_github
get:
  path: secrets
  name: token_github_storezhang
---


kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    pull: always
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      compress:
        enabled: false

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    pull: always
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    pull: always
    when:
      event:
        - tag
    environment:
      TOKEN_GITHUB:
        from_secret: token_github
    settings:
      release:
        tag: $${DRONE_TAG}
        token: $${TOKEN_GITHUB}
        body: file('$${CHANGELOG_TAG_OUTPUT}')


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
